### PR TITLE
Bug fixes: tfsec log, duplicate/non existent checks, flow fix

### PR DESCRIPTION
**Pull request by penenadpi**
Applying this commit: 
- tfsec log will not contain unreadable characters, wrongly-interpreted spaces and new line characters like "[....m", "\n",  either in JSON or HTML format
- It won't be possible to add non-existent or duplicate checks to the project
- the flow of project check list loading without configuration object previously assigned is fixed

### CODE REVIEW

**Review by RedekG — COMMENTED** [review]
Please skip commit fceea2f15ac9a0ba9db33ad06c9cf419117fe24a since is the same as in https://github.com/xlab-si/iac-scan-runner/pull/38.

Otherwise LGTM.

**Comment by penenadpi** [comment]
Removed the duplicate commit

**Comment by penenadpi** [comment]
Should be ready to merge

**Review by RedekG — APPROVED** [review]
LGTM

**Pull request merged**
